baseURL = "https://cfeclipse.org/"
languageCode = "en-us"
title = "CFEclipse"
theme = 'beautifulhugo'

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "CFML Editor for Eclipse"
  mainSections = ["post","posts"]
  logo = "img/logo.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = false
  readingTime = false
  wordCount = false
  useHLJS = false
  socialShare = false
  delayDisqus = true
  showRelatedPosts = false
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Andrew Myers"
  website = "cfeclipse.org"
  email = "amyers@cfeclipse.org"
  github = "cfeclipse"

[[menu.main]]
    name = "Github"
    url = "https://github.com/cfeclipse"
    weight = 1

[[menu.main]]
    name = "Contributors"
    url = "page/contributors/"
    weight = 2
